name: Diff checker
runs:
  using: "composite"
  steps:
    - name: Get main branch commit
      id: getSinceCommit
      run: |
        commit=$(git merge-base HEAD origin/${{ github.event.repository.default_branch }})
        echo "::set-output name=sinceCommit::${commit}"
      shell: bash
    - name: Get current branch commit
      id: getNowCommit
      run: |
        commit=$(git log -1 | grep "^commit" | awk '{print $2}')
        echo "::set-output name=nowCommit::${commit}"
      shell: bash
    - name: Check both commit
      if: ${{ steps.getSinceCommit.outputs.sinceCommit == steps.getNowCommit.outputs.nowCommit }}
      run: exit 1
      shell: bash