name: My workflow

on: push

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get main branch commit
        id: getSinceCommit
        run: |
            echo ${ git merge-base HEAD origin/${{ github.event.repository.default_branch }} }
            echo "::set-output name=sinceCommit::sc"
      - name: Print main branch commit
        run: echo "${{ steps.getSinceCommit.outputs.sinceCommit }}"
      - name: Current branch
        run: echo ${GITHUB_REF##*/}


