name: My workflow

on: push

jobs:
  check-diff:
    if: github.event.repository.default_branch != ${GITHUB_REF#refs/heads/}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - run: echo ${GITHUB_REF#refs/heads/}
      - name: Get main branch commit
        id: getSinceCommit
        run: |
          commit=$(git merge-base HEAD origin/${{ github.event.repository.default_branch }})
          echo "::set-output name=sinceCommit::${commit}"
      - name: Get current branch commit
        id: getNowCommit
        run: |
          commit=$(git log -1 | grep "^commit" | awk '{print $2}')
          echo "::set-output name=nowCommit::${commit}"
      - name: Check both commit
        if: ${{ steps.getSinceCommit.outputs.sinceCommit == steps.getNowCommit.outputs.nowCommit }}
        run: exit 1

