name: My workflow

on: push

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get main branch commit
        id: getSinceCommit
        run: |
            commit=$(git merge-base HEAD origin/${{ github.event.repository.default_branch }})
            echo "::set-output name=sinceCommit::${commit}"
      - name: Get current branch commit
        id: getNowCommit
        run: |
            commit=$(git log -1 | grep "^commit" | awk '{print $2}')
            echo "::set-output name=nowCommit::${commit}"
      - name: Check both commit
        if: ${{ steps.getSinceCommit.outputs.sinceCommit != steps.getNowCommit.outputs.nowCommit }}
        run: |
            echo "${{ steps.getSinceCommit.outputs.sinceCommit }}"
            echo "${{ steps.getNowCommit.outputs.nowCommit }}"
            echo failing step
            exit 1

