name: Validate code

on: 
  workflow_call

jobs:
  Linting:
    needs: Diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Node version
        run: node --version
      - name: Checking code guidelines
        run: npm run lint
  Testing:
    needs: Diff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - name: Node version
        run: node --version
      - name: Testing code
        run: npm run test